Web/Olympia.Web/Areas/AreaAdministration/Controllers/AdministrationController.cs
namespace Olympia.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Data.Models.BindingModels.Blogs;
    using Olympia.Data.Models.BindingModels.Shop;
    using Olympia.Services.Contracts;

    using System.Linq;
    using System.Threading.Tasks;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area(GlobalConstants.AdministrationArea)]
    public class AdministrationController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IBlogService blogService;
        private readonly IShopService shopService;
        private readonly IFitnessService fitnessService;

        public AdministrationController(
            IUsersService usersService,
            IBlogService blogService,
            IShopService shopService,
            IFitnessService fitnessService)
        {
            this.usersService = usersService;
            this.blogService = blogService;
            this.shopService = shopService;
            this.fitnessService = fitnessService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult CreateArticle()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateArticle(CreateArticleBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.blogService.CreateArticleAsync(model, this.User.Identity.Name);
            var articles = await this.blogService.GetAllArticlesAsync();
            return this.View("ArticlesAll", articles);
        }

        public async Task<IActionResult> UsersAll()
        {
            var users = await this.usersService.GetAllUsersAsync();
            return this.View(users);
        }

        public async Task<IActionResult> ArticlesAll()
        {
            var articles = await this.blogService.GetAllArticlesAsync();
            return this.View(articles);
        }

        public async Task<IActionResult> ItemsAll()
        {
            var items = await this.fitnessService.GetAllItemsAsync();
            return this.View(items);
        }

        public async Task<IActionResult> DeleteUser(string username)
        {
            await this.usersService.DeleteUserAsync(username);
            var users = await this.usersService.GetAllUsersAsync();

            return this.View("UsersAll", users);
        }

        public async Task<IActionResult> DeleteArticle(int articleId)
        {
            await this.blogService.DeleteArticleByIdAsync(articleId);
            return this.Redirect(GlobalConstants.AdministrationArticles);
        }

        public async Task<IActionResult> AddItem()
        {
            var names = (await this.fitnessService.GetAllSuppliersAsync()).Select(x => x.Name);
            return this.View(new ItemBindingModel() { SupplierNames = names });
        }

        public IActionResult CreateItem()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateItem(ItemBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View("AddItem", model);
            }

            await this.shopService.CreateItemAsync(model);
            return this.View("Success");
        }

        public IActionResult AddSupplier()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSupplier(SupplierBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var action = await this.fitnessService.AddSupplierAsync(model);

            if (!action)
            {
                this.ViewData["Errors"] = GlobalConstants.SameSupplierErrorMessage;
                return this.View(model);
            }

            var suppliers = await this.fitnessService.GetAllSuppliersAsync();
            return this.View("SuppliersAll", suppliers);
        }

        public async Task<IActionResult> SuppliersAll()
        {
            var suppliers = await this.shopService.GetAllSuppliersAsync();
            return this.View(suppliers);
        }

        public async Task<IActionResult> DeleteItem(int itemId)
        {
            await this.shopService.DeleteItemAsync(itemId);
            var items = await this.fitnessService.GetAllItemsAsync();

            return this.View("ItemsAll", items);
        }
        public async Task<IActionResult> UserDetails(string username)
        {
            var user = await this.usersService.GetUserByUsernameAsync(username);
            return this.View(user);
        }
    }
}

Web/Olympia.Web/Areas/AreaBlog/Controllers/BlogController.cs
namespace Olympia.Web.Areas.Blog.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Services.Contracts;

    using System.Threading.Tasks;

    [Area(GlobalConstants.BlogArea)]
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogService blogService;

        public BlogController(IBlogService blogService)
        {
            this.blogService = blogService;
        }

        public async Task<IActionResult> ArticlesAll()
        {
            var articles = await this.blogService.GetAllArticlesAsync();
            return this.View(articles);
        }

        public async Task<IActionResult> ArticleDetails(int articleId)
        {
            var article = await this.blogService.GetArticleAndIncrementTimesReadAsync(articleId);
            return this.View(article);
        }
    }
}

Web/Olympia.Web/Areas/AreaShop/Controllers/ShopController.cs
namespace Olympia.Web.Areas.Shop.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Data.Models.ViewModels.Shop;
    using Olympia.Services.Contracts;

    using System.Linq;
    using System.Threading.Tasks;

    [Area(GlobalConstants.ShopArea)]
    [Authorize]
    public class ShopController : Controller
    {
        private readonly IShopService shopService;

        public ShopController(IShopService shopService)
        {
            this.shopService = shopService;
        }

        public async Task<IActionResult> ShopIndex()
        {
            var items = await this.shopService.GetAllItemsAsync();
            ShopViewModel shopViewModel = new ShopViewModel { Items = items };

            return this.View(shopViewModel);
        }

        public async Task<IActionResult> Items(string categoryName)
        {
            var items = await this.shopService.GetAllItemsByCategoryAsync(categoryName);

            foreach (var item in items)
            {
                item.Category = categoryName;
            }

            var shoppingCart = await this.shopService.GetShoppingCartByUserNameAsync(this.User.Identity.Name);
            var shopViewModel = new ShopViewModel() { Items = items, ShoppingCart = shoppingCart };

            return this.View("ItemsAll", shopViewModel);
        }

        public async Task<IActionResult> ItemDetails(int itemId, string category)
        {
            var item = await this.shopService.GetItemDtoByIdAsync(itemId);
            item.Category = category;

            return this.View(item);
        }

        public async Task<IActionResult> AddToCart(int itemId, string category)
        {
            var result = await
                this.shopService
                .AddItemToUserCartAsync(itemId, this.User.Identity.Name);

            if (!result)
            {
                this.ViewData["Errors"] = GlobalConstants.AlreadyAddedThisItem;
            }

            var cart = await this.shopService.GetShoppingCartByUserNameAsync(this.User.Identity.Name);
            var items = await this.shopService.GetAllItemsByCategoryAsync(category);

            ShopViewModel shopViewModel = new ShopViewModel
            {
                Items = items,
                ShoppingCart = cart
            };

            return this.View("ItemsAll", shopViewModel);
        }

        public async Task<IActionResult> ShoppingCart()
        {
            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);
            return this.View(cart);
        }

        public async Task<IActionResult> RemoveFromCart(int itemId)
        {
            await this.shopService.RemoveFromCartAsync(this.User.Identity.Name, itemId);
            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);

            return this.View("ShoppingCart", cart);
        }

        public async Task<IActionResult> IncreaseCount(int itemId)
        {
            await this.shopService.IncreaseTimesItemIsBoughtAsync(itemId);
            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);

            return this.View("ShoppingCart", cart);
        }

        public async Task<IActionResult> DecreaseCount(int itemId)
        {
            await this.shopService.DecreaseTimesItemIsBoughtAsync(itemId);
            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);

            return this.View("ShoppingCart", cart);
        }

        public async Task<IActionResult> FinishOrder()
        {
            var result = await this.shopService.FinishOrderAsync(this.User.Identity.Name);
            this.ViewData["Messages"] = GlobalConstants.SuccessfullOrderMessage;

            if (!result)
            {
                this.ViewData["Messages"] = GlobalConstants.NoItemsInCartMessage;
            }

            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);
            return this.View("ShoppingCart", cart);
        }

        public async Task<IActionResult> MyOrders()
        {
            var orders = await this.shopService.GetAllOrdersByUsernameAsync(this.User.Identity.Name);

            if (!orders.Any())
            {
                this.ViewData["Errors"] = GlobalConstants.NoOrdersMessage;
            }

            return this.View(orders);
        }

        public async Task<IActionResult> CompleteOrder(int orderId)
        {
            var result = await this.shopService.CompleteOrderAsync(orderId);

            if (!result)
            {
                this.ViewData["Errors"] = GlobalConstants.TooEarlyFinishOrderDate;
                var ordersToReturn = await this.shopService.GetAllOrdersByUsernameAsync(this.User.Identity.Name);

                return this.View("MyOrders", ordersToReturn);
            }

            var orders = await this.shopService.GetAllOrdersByUsernameAsync(this.User.Identity.Name);

            if (!orders.Any())
            {
                this.ViewData["Errors"] = GlobalConstants.NoOrdersMessage;
            }

            return this.View("MyOrders", orders);
        }
    }
}

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/AddItem.cshtml
@{
    @model Olympia.Data.Models.BindingModels.Shop.ItemBindingModel
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "AddItem";
}

<div class="container container-fluid">
    <form method="post" enctype="multipart/form-data"
          asp-area="AreaAdministration"
          asp-controller="Administration"
          asp-action="CreateItem"
          asp-antiforgery="true">
        <h4>Create a new item.</h4>
        <hr class="w-100" />
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="@Model.CategoryName"></label>
            <select asp-for="@Model.CategoryName" class="form-control" asp-items="@Html.GetEnumSelectList<Olympia.Data.Models.BindingModels.Shop.Category>()"></select>
            <span asp-validation-for="@Model.CategoryName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.SupplierName"></label>
            <select asp-for="@Model.SupplierName" class="form-control" asp-items="@(new SelectList(Model.SupplierNames))"></select>
            <span asp-validation-for="@Model.SupplierName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Name"></label>
            <input type="text" asp-for="@Model.Name" class="form-control" />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Price"></label>
            <input type="number" asp-for="@Model.Price" class="form-control" step="0.01" />
            <span asp-validation-for="@Model.Price" class="text-danger"></span>
        </div>
        <div class="d-flex justify-content-around">

            <div class="form-group mr-3">
                <label asp-for="@Model.Description"></label>
                <textarea type="text" asp-for="@Model.Description" class="form-control" cols="30" rows="10"></textarea>
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.ImgUrl"></label>
                <input type="file" asp-for="@Model.ImgUrl" class="form-control-file" />
                <span asp-validation-for="@Model.ImgUrl" class="text-danger"></span>
            </div>
        </div>
        <button class="btn btn-danger form-control mt-5">
            Create
        </button>
    </form>
</div>

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/AddSupplier.cshtml
@{
    ViewData["Title"] = "AddSupplier";
    @model Olympia.Data.Models.BindingModels.Shop.SupplierBindingModel
}

<div class="container container-fluid">
    <form method="post" class="form-group"
          asp-area="AreaAdministration"
          asp-controller="Administration"
          asp-action="AddSupplier"
          asp-antiforgery="true">
        <h1 class="text-center">Add Supplier</h1>
        <hr class="w-100" />
        <div class="form-group">
            @if (this.ViewData["Errors"] != null)
            {
                <h5 class="text-danger">@this.ViewData["Errors"]</h5>
            }
            <div class="form-group">
                <label asp-for="@Model.Name"></label>
                <input type="text" asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Description"></label>
                <textarea type="text" asp-for="@Model.Description" rows="10" cols="75" class="form-control"></textarea>
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>
        </div>
        <div>
            <button class="btn btn-danger form-control">Add Supplier</button>
        </div>
    </form>
</div>

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/ArticlesAll.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "ArticlesAll";
    @model IEnumerable<Olympia.Data.Models.ViewModels.BlogPartViewModels.ArticleViewModel>
}

<div>
    <a class="btn btn-danger"
       asp-area="AreaAdministration"
       asp-controller="Administration"
       asp-action="CreateArticle">New Article</a>
</div>

@if (Model.Any())
{
    <div>
        <div class="container">
            <div class="row">
                @foreach (var article in Model)
                {
                    <div class="card col-md-9 mt-3 mb-3 mr-3 ml-3">
                        <img class="card-img" src="@article.ImgUrl" alt="Bologna">
                        <div class="card-body">
                            <h4 class="card-title">@article.Title</h4>
                            <p class="card-text">@string.Join("", article.Content.Take(75))...</p>
                            <h5>Author: @article.Author.FullName</h5>
                            <a asp-area="AreaBlog"
                               asp-controller="Blog"
                               asp-action="ArticleDetails"
                               asp-route-articleId="@article.Id" class="btn btn-info">Read Me</a>
                        </div>
                        <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
                            <div class="views">
                                @article.CreatedOn
                            </div>
                            <div class="stats">
                                <i class="far fa-eye"></i> @article.TimesRead
                            </div>

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
}
else
{
    <h3 class="text-danger text-center">There are currently no articles.</h3>
}

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/CreateArticle.cshtml
@{
    ViewData["Title"] = "CreateArticle";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model Olympia.Data.Models.BindingModels.Blogs.CreateArticleBindingModel
}


<h1>CreateArticle</h1>
<form class="form-group" method="post" enctype="multipart/form-data"            
      asp-area="AreaAdministration"
      asp-controller="Administration"
      asp-action="CreateArticle"
      asp-antiforgery="true" >
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="@Model.Title"></label>
        <input asp-for="@Model.Title" class="form-control" />
        <span asp-validation-for="@Model.Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Content"></label>
        <textarea asp-for="@Model.Content" class="form-control" rows="5" cols="60">
            Enter details here...
         </textarea>        
        <span asp-validation-for="@Model.Content" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.ImgUrl"></label>
        <input type="file" asp-for="@Model.ImgUrl" class="form-control-file" multiple>
        <span asp-validation-for="@Model.ImgUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/Index.cshtml
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
    this.ViewData["Title"] = "Аdmin";
}

<form method="get"
      class="form-group"
      asp-antiforgery="true">
    <div class="">
        <button class="btn btn-success form-control mb-3"
                asp-area="AreaAdministration"
                asp-controller="Administration"
                asp-action="UsersAll">
            Users
        </button>
        <button class="btn btn-success form-control mb-3"
                asp-area="AreaAdministration"
                asp-controller="Administration"
                asp-action="ArticlesAll">
            Articles
        </button>
        <button class="btn btn-success form-control mb-3"
                asp-area="AreaAdministration"
                asp-controller="Administration"
                asp-action="ItemsAll">
            Items
        </button>
        <button class="btn btn-success form-control mb-3"
                asp-area="AreaAdministration"
                asp-controller="Administration"
                asp-action="SuppliersAll">
            Suppliers
        </button>
    </div>
</form>

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/ItemsAll.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "ItemsAll";
    @model Olympia.Data.Models.ViewModels.Shop.ShopViewModel
}

<div class="row">
    <h1 class="text-lg-center col-sm-8">All Items</h1>

    <div class="col-sm-2">
        <a asp-area="AreaAdministration"
           asp-controller="Administration"
           asp-action="AddItem" class="btn btn-danger">Add Item</a>
    </div>

    <div class="col-sm-2">
        <a asp-area="AreaAdministration"
           asp-controller="Administration"
           asp-action="AddSupplier" class="btn btn-danger">Add Supplier</a>
    </div>

</div>
<div class="container">
    <div class="row">
        @if (Model.Items.Any())
        {
            @foreach (var item in Model.Items)
            {
                <div class="col-md-3 card mr-5 mb-4">
                    <i><h5 class="card-header text-center">@item.Name</h5></i>
                    <img class="card-img" src="@item.ImgUrl" alt="Loading..." />
                    <div class="d-flex justify-content-center">
                        <strong><p class="text-center">@item.Supplier.Name</p></strong>
                    </div>
                    <div class="d-flex justify-content-center row">
                        <a class="btn btn-danger col-lg-5 mb-2 mr-2"
                           asp-area="AreaShop"
                           asp-controller="Shop"
                           asp-action="AddToCart"
                           asp-route-itemId="@item.Id">Add To Cart</a>
                        <a class="btn btn-danger col-lg-5 mb-2"
                           asp-area="AreaShop"
                           asp-controller="Shop"
                           asp-action="ItemDetails"
                           asp-route-itemId="@item.Id">Details</a>                        
                    </div>
                </div>
            }
        }
        else
        {
            <h3 class="mt-5">No items in the shop</h3>
        }
    </div>
</div>

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/Success.cshtml
@{
    ViewData["Title"] = "TrainersAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-success text-center">Successfully added item! </h2>

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/SuppliersAll.cshtml
@{
    ViewData["Title"] = "SuppliersAll";
    @model IEnumerable<Olympia.Data.Domain.Supplier>
}

<div class="container container-fluid">
    <div>
        <h2 class="text-center text-danger mb-5 mt-2">Suppliers</h2>
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Supplier's name</th>
                    <th scope="col">Count of items</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var supplier in Model)
                {
                    <tr>                        
                        <td>@supplier.Name</td>
                        <td>@supplier.Items.Count</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/UserDetails.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "ClientDetails";
    @model Olympia.Data.Domain.OlympiaUser
}

<h2 class="text-danger text-center">@Model.FullName</h2>
<hr class="bg-danger" />

<div class="container">
    <div class="row">
        <div class="d-flex justify-content-between">
            <div>
                <div class="row">
                    <h3 class="col-md-12 text-danger mb-5">Age: @Model.Age</h3>
                    <h3 class="col-md-12 text-danger mb-5">Gender: @Model.Gender</h3>
                    <h3 class="col-md-12 text-danger mb-5">Weight: @Model.Weight</h3>
                    <h3 class="col-md-12 text-danger mb-5">Height: @Model.Height</h3>
                </div>
            </div>
            <div class="card card-trainer ml-4">
                <img src="@Model.ProfilePicturImgUrl" alt="Loading..." style="width:100%">
                <h3>@Model.FullName</h3>
                <p class="title">Olympia Client</p>
            </div>
        </div>
    </div>
    <div class="row">
        <a class="btn btn-primary col-md-12 mt-5 text-light"
           data-toggle="modal" data-target="#adminUserDeleteModal">Delete User</a>

        <div class="modal fade" id="adminUserDeleteModal" tabindex="-1" role="dialog" aria-labelledby="adminItemDeleteLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete article</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure to delete @Model.UserName?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <a type="button" class="btn btn-primary"
                           asp-area="AreaAdministration"
                           asp-controller="Administration"
                           asp-action="DeleteUser"
                           asp-route-username="@Model.UserName">
                            Confirm
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Olympia.Web/Areas/AreaAdministration/Views/Administration/UsersAll.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "UsersAll";
    @model IEnumerable<Olympia.Data.Models.ViewModels.AdminViewModels.ListedUserViewModel>
}
@if (Model.Any())
{
    <div class="container">
        <div class="row">
            @foreach (var user in Model)
            {
                <div class="card col-md-4 mb-4">
                    <h3 class="mb-4 position-relative">@user.UserName - @user.FullName</h3>
                    <img class="ml-5" src="@user.ProfilePicturImgUrl" alt="Loading..." style="height:80%;width:60%" />

                    <a class="btn btn-primary mt-4 text-light"
                       asp-area="AreaAdministration"
                       asp-controller="Administration"
                       asp-action="UserDetails"
                       asp-route-username="@user.UserName">
                        Details
                    </a>
                </div>
            }
        </div>
    </div>
}
else
{
    <h3 class="text-danger text-center">There are currently no users.</h3>
}