Web/Olympia.Web/Areas/AreaBlog/Controllers/BlogController.cs
namespace Olympia.Web.Areas.Blog.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Services.Contracts;

    using System.Threading.Tasks;

    [Area(GlobalConstants.BlogArea)]
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogService blogService;

        public BlogController(IBlogService blogService)
        {
            this.blogService = blogService;
        }

        public async Task<IActionResult> ArticlesAll()
        {
            var articles = await this.blogService.GetAllArticlesAsync();
            return this.View(articles);
        }

        public async Task<IActionResult> ArticleDetails(int articleId)
        {
            var article = await this.blogService.GetArticleAndIncrementTimesReadAsync(articleId);
            return this.View(article);
        }
    }
}

Web/Olympia.Web/Areas/AreaTrainer/Controllers/TrainerController.cs
namespace Olympia.Web.Areas.Trainer.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Data.Models.BindingModels.Blogs;
    using Olympia.Data.Models.BindingModels.Client;
    using Olympia.Data.Models.ViewModels.Fitness;
    using Olympia.Services.Contracts;

    using System.Linq;
    using System.Threading.Tasks;

    [Area(GlobalConstants.TrainerArea)]
    [Authorize(Roles = GlobalConstants.TrainerAdministratorRoleName)]
    public class TrainerController : Controller
    {
        private readonly IBlogService blogService;
        private readonly IUsersService usersService;
        private readonly IFitnessService fitnessService;

        public TrainerController(
            IBlogService blogService,
            IUsersService usersService,
            IFitnessService fitnessService)
        {
            this.blogService = blogService;
            this.usersService = usersService;
            this.fitnessService = fitnessService;
        }

        public async Task<IActionResult> ClientsAll()
        {
            var clients = await this.usersService.GetAllClientsByUserAsync(this.User.Identity.Name);

            if (clients.Count() == 0)
            {
                this.ViewData["Errors"] = GlobalConstants.NoClientsMessage;
            }

            return this.View(clients);
        }

        public async Task<IActionResult> MyArticles()
        {
            var currentUserArticles = await this.blogService.GetAllByUserIdAsync(this.User.Identity.Name);
            return this.View(currentUserArticles);
        }

        public IActionResult CreateArticle()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateArticle(CreateArticleBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.blogService.CreateArticleAsync(model, this.User.Identity.Name);
            return this.Redirect(GlobalConstants.TrainerMyArticles);
        }

        public async Task<IActionResult> DeleteArticle(int articleId)
        {
            await this.blogService.DeleteArticleByIdAsync(articleId);
            return this.Redirect(GlobalConstants.TrainerMyArticles);
        }

        public async Task<IActionResult> ClientDetails(string username)
        {
            var user = await this.usersService.GetUserByUsernameAsync(username);
            return this.View(user);
        }

        public async Task<IActionResult> CreateFitnessPlan(string username)
        {
            var model = await this.usersService.GetUserWithFitnessPlanModelAsync(username);
            return this.View(model);
        }

        public IActionResult ChooseWorkout(ClientViewModel model)
        {
            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FileterWorkouts(ClientViewModel model)
        {
            if (model.WorkoutInputModel.Duration == 0 ||
                model.WorkoutInputModel.WorkoutDifficulty == 0 ||
                model.WorkoutInputModel.WorkoutType == 0)
            {
                return this.View("ChooseWorkout", model);
            }

            model.Workouts = await this.fitnessService.GetWorkoutsAsync(model.WorkoutInputModel);
            model.WeekWorkoutDuration = model.WorkoutInputModel.Duration;

            return this.View("Workouts", model);
        }

        public async Task<IActionResult> CalculateCalories(ClientViewModel user)
        {
            var calories = await this.usersService.CalculateCaloriesAsync(user.UserName);
            user.Calories = calories;

            return this.View("CreateFitnessPlan", user);
        }

        public async Task<IActionResult> AssignFitnessPlan(ClientViewModel user, int workoutId)
        {
            var workout = await this.fitnessService.GetWorkoutByIdAsync(workoutId);
            user.WorkoutViewModel = workout;

            return this.View("CreateFitnessPlan", user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetFitnessPlan(ClientViewModel model, int workoutId)
        {
            model.WorkoutViewModel = await this.fitnessService.GetWorkoutByIdAsync(workoutId);

            if (model.Calories == 0 || model.WorkoutViewModel == null)
            {
                model.WorkoutViewModel = new WorkoutViewModel() { Name = "", ImgUrl = "" };
                this.ViewData["Errors"] = GlobalConstants.UnFilledFitnessPlanFieldsMessage;

                return this.View("CreateFitnessPlan", model);
            }

            await this.usersService.SetFitnessPlanToUserAsync(model);
            var clients = await this.usersService.GetAllClientsByUserAsync(this.User.Identity.Name);

            return this.View("ClientsAll", clients);
        }
    }
}

Web/Olympia.Web/Areas/AreaTrainer/Views/Trainer/ChooseWorkout.cshtml
@{
    ViewData["Title"] = "ChooseWorkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model Olympia.Data.Models.BindingModels.Client.ClientViewModel
}

<div class="container">
    <h4 class="text-center">
        Select Difficulty
    </h4>
    <div class="row">
        <form method="post"
               asp-antiforgery="true"
              class="form-group d-flex justify-content-between">
            <br />
            <div class="mr-3 col-xl-6 sr-only-focusable text-center">
                <h5>Difficulty</h5>
                <select asp-for="@Model.WorkoutInputModel.WorkoutDifficulty" class="form-control" asp-items="@Html.GetEnumSelectList<Olympia.Data.Domain.Enums.WorkoutDifficulty>()"></select>
                <span asp-validation-for="@Model.WorkoutInputModel.WorkoutDifficulty" class="text-danger"></span>
            </div>
            <div class="mr-3 col-xl-6 sr-only-focusable text-center">
                <h5>Intermediate</h5>
                <select asp-for="@Model.WorkoutInputModel.WorkoutType" class="form-control" asp-items="@Html.GetEnumSelectList<Olympia.Data.Domain.Enums.WorkoutType>()"></select>
                <span asp-validation-for="@Model.WorkoutInputModel.WorkoutType" class="text-danger"></span>
            </div>
            <div class="mr-3 col-xl-6 sr-only-focusable  text-center">
                <h5>Duration</h5>
                <select asp-for="@Model.WorkoutInputModel.Duration" class="form-control" asp-items="@Html.GetEnumSelectList<Olympia.Data.Domain.Enums.WeekWorkoutDuration>()"></select>
                <span asp-validation-for="@Model.WorkoutInputModel.Duration" class="text-danger"></span>
            </div>
            <button class="btn btn-primary" 
                    asp-area="AreaTrainer"
                    asp-controller="Trainer"
                    asp-action="FileterWorkouts"
                    asp-route-fullname="@Model.FullName"
                    asp-route-weight="@Model.Weight"
                    asp-route-height="@Model.Height"
                    asp-route-age="@Model.Age"
                    asp-route-activity="@Model.Activity"
                    asp-route-gender="@Model.Gender"
                    asp-route-username="@Model.UserName"
                    asp-route-calories="@Model.Calories"
                    asp-route-workoutdifficulty="@Model.WorkoutViewModel.WorkoutDifficulty"
                    asp-route-workout="@Model.WorkoutViewModel.WorkoutType"
                    asp-route-weekworkoutduration="@Model.WorkoutInputModel.Duration"
                    >
                Filter Workouts
            </button>
        </form>
    </div>
</div>

Web/Olympia.Web/Areas/AreaTrainer/Views/Trainer/ClientDetails.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "ClientDetails";
    @model Olympia.Data.Domain.OlympiaUser
}

<h2 class="text-danger text-center">@Model.FullName</h2>
<hr class="bg-danger" />

<div class="container">
    <div class="row">
        <div class="d-flex justify-content-between">
            <div>
                <div class="row">
                    <h3 class="col-md-12 text-danger mb-5">Age: @Model.Age</h3>
                    <h3 class="col-md-12 text-danger mb-5">Gender: @Model.Gender</h3>
                    <h3 class="col-md-12 text-danger mb-5">Weight: @Model.Weight</h3>
                    <h3 class="col-md-12 text-danger mb-5">Height: @Model.Height</h3>
                </div>               
            </div>
            <div class="card card-trainer ml-4">
                <img src="@Model.ProfilePicturImgUrl" alt="Loading..." style="width:100%">
                <h3>@Model.FullName</h3>
                <p class="title">Olympia Client</p>
            </div>
        </div>
    </div>
    <div class="row">
        <a asp-area="AreaTrainer"
                asp-controller="Trainer"
                asp-action="CreateFitnessPlan"
                asp-route-username="@Model.UserName"
           class="btn btn-primary col-md-12 mt-5">Create Fitness Plan</a>
    </div>
</div>

Web/Olympia.Web/Areas/AreaTrainer/Views/Trainer/ClientsAll.cshtml
@{
    ViewData["Title"] = "ClientsAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model IEnumerable<Olympia.Data.Models.ViewModels.BlogPartViewModels.UserViewModel>
    int index = 1;
}

@if (Model.Any())
{
    <h1 class="text-center">ClientsAll</h1>

    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full Name</th>
                <th scope="col">Username</th>
                <th scope="col">Age</th>
                <th scope="col">Weight</th>
                <th scope="col">Height</th>
                <th scope="col">Gender</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var client in Model)
            {
                <tr data-href="/AreaTrainer/Trainer/ClientDetails?username=@client.Username">
                    <td scope="row">@(index++)</td>
                    <td>@client.FullName</td>
                    <td>@client.Username</td>
                    <td>@client.Age</td>
                    <td>@(string.IsNullOrEmpty(client.Weight) ? "-" : client.Height)</td>
                    <td>@(string.IsNullOrEmpty(client.Height) ? "-" : client.Height)</td>
                    <td>@client.Gender.ToString()</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4 class="text-center text-danger">@this.ViewData["Errors"]</h4>
}

Web/Olympia.Web/Areas/AreaTrainer/Views/Trainer/CreateArticle.cshtml
@{
    ViewData["Title"] = "CreateArticle";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model Olympia.Data.Models.BindingModels.Blogs.CreateArticleBindingModel
}


<h1>CreateArticle</h1>
<form class="form-group" method="post" enctype="multipart/form-data"     
      asp-area="AreaTrainer"
      asp-controller="Trainer"
      asp-action="CreateArticle"     
      asp-antiforgery="true" >
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="@Model.Title"></label>
        <input asp-for="@Model.Title" class="form-control" />
        <span asp-validation-for="@Model.Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Content"></label>
        <textarea asp-for="@Model.Content" class="form-control" rows="5" cols="60">
            Enter details here...
         </textarea>        
        <span asp-validation-for="@Model.Content" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.ImgUrl"></label>
        <input type="file" asp-for="@Model.ImgUrl" class="form-control-file" multiple>
        <span asp-validation-for="@Model.ImgUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>

Web/Olympia.Web/Areas/AreaTrainer/Views/Trainer/CreateFitnessPlan.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model Olympia.Data.Models.BindingModels.Client.ClientViewModel
    ViewData["Title"] = "CreateFitnessPlan";
}

<h1 class="text-lg-center">Fitness plan for @Model.FullName</h1>

<form method="post"
      asp-antiforgery="true">
    <hr />
    @if (this.ViewData["Errors"] != null)
    {
        <h4 class="text-danger">@this.ViewData["Errors"]</h4>
    }
    <div class="form-group">
        <label asp-for="@Model.Weight"></label>
        <input disabled type="number" asp-for="@Model.Weight" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Height"></label>
        <input disabled type="number" asp-for="@Model.Height" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Age"></label>
        <input disabled type="number" asp-for="@Model.Age" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Gender"></label>
        <input disabled type="text" asp-for="@Model.Gender" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Calories"></label>
        <input disabled type="number" asp-for="@Model.Calories" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.WorkoutViewModel.Name">Workout name</label>
        <input disabled type="text" asp-for="@Model.WorkoutViewModel.Name" class="form-control" />
    </div>
    <div class="form-group">
        <div class="d-flex form-inline justify-content-between">
            <div>
                <button type="submit" class="btn btn-primary"
                        asp-area="AreaTrainer"
                        asp-controller="Trainer"
                        asp-action="CalculateCalories"
                        asp-route-FullName="@Model.FullName"
                        asp-route-weight="@Model.Weight"
                        asp-route-height="@Model.Height"
                        asp-route-age="@Model.Age"
                        asp-route-workoutId="@Model.WorkoutViewModel.Id"
                        asp-route-activity="@Model.Activity"
                        asp-route-gender="@Model.Gender"
                        asp-route-username="@Model.UserName">
                    Calculate Calories
                </button>
                <button type="submit" class="btn btn-primary"
                        asp-area="AreaTrainer"
                        asp-controller="Trainer"
                        asp-action="ChooseWorkout"
                        asp-route-FullName="@Model.FullName"
                        asp-route-weight="@Model.Weight"
                        asp-route-height="@Model.Height"
                        asp-route-age="@Model.Age"
                        asp-route-activity="@Model.Activity"
                        asp-route-workoutId="@Model.WorkoutViewModel.Id"
                        asp-route-gender="@Model.Gender"
                        asp-route-username="@Model.UserName"
                        asp-route-calories="@Model.Calories">
                    Choose Workout
                </button>
            </div>
            <button class="btn btn-danger"
                    asp-area="AreaTrainer"
                    asp-controller="Trainer"
                    asp-action="SetFitnessPlan"
                    asp-route-fullname="@Model.FullName"
                    asp-route-weight="@Model.Weight"
                    asp-route-height="@Model.Height"
                    asp-route-age="@Model.Age"
                    asp-route-activity="@Model.Activity"
                    asp-route-gender="@Model.Gender"
                    asp-route-username="@Model.UserName"
                    asp-route-calories="@Model.Calories"
                    asp-route-workoutId="@Model.WorkoutViewModel.Id"
                    asp-route-weekworkoutduration="@Model.WeekWorkoutDuration">
                Create
            </button>
        </div>
    </div>  
</form>

Web/Olympia.Web/Areas/AreaTrainer/Views/Trainer/MyArticles.cshtml
@{
    ViewData["Title"] = "MyArticles";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model IEnumerable<Olympia.Data.Models.ViewModels.BlogPartViewModels.ArticleViewModel>
    var list = Model.ToList();
}

<div>
    <a class="btn btn-danger" 
       asp-area="AreaTrainer" 
       asp-controller="Trainer" 
       asp-action="CreateArticle">New Article</a>
</div>
<div>
    <h3 class="text-center text-danger">You have written: @list.Count() Article(s)</h3>
</div>
<div>
    <div class="container">
        <div class="row">
            @foreach (var article in list)
            {
                <div class="col-md-12 card mt-3 mb-3 mr-3 ml-3" style="background:#f0ffff">
                    <img class="card-img" src="@article.ImgUrl" alt="Bologna">
                    <div class="card-body">
                        <h4 class="card-title">@article.Title</h4>
                        <p class="card-text">@string.Join("", article.Content.Take(75))...</p>
                        <a asp-area="AreaBlog"
                           asp-controller="Blog" 
                           asp-action="ArticleDetails" 
                           asp-route-articleId="@article.Id" class="btn btn-info">Read Me</a>
                    </div>
                    <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
                        <div class="views">
                            @article.CreatedOn
                        </div>
                        <div class="stats">
                            <i class="far fa-eye"></i> @article.TimesRead
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Web/Olympia.Web/Areas/AreaTrainer/Views/Trainer/Workouts.cshtml
@{
    ViewData["Title"] = "Workouts";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model Olympia.Data.Models.BindingModels.Client.ClientViewModel
}

<div class="container">
    <div class="row">
        @foreach (var item in Model.Workouts)
        {
            <div class="col-md-12 card">
                <h3>@item.Name</h3>
                <hr class="w-100" />
                <div class="card-body">
                    <img class="card-img-top mb-4" src="@item.ImgUrl" alt="Unavailabe" />
                    @foreach (var exerciese in item.Exercises)
                    {
                        <h5>@exerciese.Name - @exerciese.Sets Sets</h5>
                        <p>Targeting body part: @exerciese.TargetBodyPart</p>
                    }
                </div>
                <p>This workout is for people who are <strong>@item.WorkoutDifficulty</strong></p>
                <h5>@item.WorkoutType</h5>
                <a class="btn btn-primary"
                   asp-area="AreaTrainer"
                   asp-controller="Trainer"
                   asp-action="AssignFitnessPlan"
                   asp-route-fullname="@Model.FullName"
                   asp-route-workoutId="@item.Id"
                   asp-route-weight="@Model.Weight"
                   asp-route-height="@Model.Height"
                   asp-route-age="@Model.Age"
                   asp-route-activity="@Model.Activity"
                   asp-route-gender="@Model.Gender"
                   asp-route-username="@Model.UserName"
                   asp-route-calories="@Model.Calories"
                   asp-route-workoutdifficulty="@item.WorkoutDifficulty"
                   asp-route-workouttype="@Model.WorkoutViewModel.WorkoutType"
                   asp-route-imgurl="@Model.WorkoutViewModel.ImgUrl"
                   asp-route-name="@Model.WorkoutViewModel.Name"
                   asp-route-id="@Model.WorkoutViewModel.Id"
                   asp-route-weekworkoutduration="@Model.WeekWorkoutDuration">
                    assign to client
                </a>
            </div>
        }
    </div>
</div>