Web/Olympia.Web/Areas/AreaBlog/Controllers/BlogController.cs
namespace Olympia.Web.Areas.Blog.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Services.Contracts;

    using System.Threading.Tasks;

    [Area(GlobalConstants.BlogArea)]
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogService blogService;

        public BlogController(IBlogService blogService)
        {
            this.blogService = blogService;
        }

        public async Task<IActionResult> ArticlesAll()
        {
            var articles = await this.blogService.GetAllArticlesAsync();
            return this.View(articles);
        }

        public async Task<IActionResult> ArticleDetails(int articleId)
        {
            var article = await this.blogService.GetArticleAndIncrementTimesReadAsync(articleId);
            return this.View(article);
        }
    }
}

Web/Olympia.Web/Areas/AreaClient/Controllers/ClientController.cs
namespace Olympia.Web.Areas.Client.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Data.Domain;
    using Olympia.Data.Models.BindingModels.Account;
    using Olympia.Data.Models.BindingModels.Client;
    using Olympia.Data.Models.ViewModels;
    using Olympia.Services.Contracts;

    using System.Linq;
    using System.Threading.Tasks;

    [Area(GlobalConstants.ClientArea)]
    [Authorize(Roles = GlobalConstants.ClientRoleName)]
    public class ClientController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IMapper mapper;
        private readonly IFitnessService fitnessService;
        private readonly SignInManager<OlympiaUser> signInManager;

        public ClientController(
            IUsersService usersService,
            IMapper mapper,
            IFitnessService fitnessService,
            SignInManager<OlympiaUser> signInManager)
        {
            this.usersService = usersService;
            this.mapper = mapper;
            this.fitnessService = fitnessService;
            this.signInManager = signInManager;
        }

        public async Task<IActionResult> TrainersAll()
        {
            var trainers = await this.usersService.GetAllTrainersAsync();

            UsernamesAndTrainerNameModel model = new UsernamesAndTrainerNameModel
            {
                Trainers = trainers,
                TrainerName = string.Empty,
            };

            if (trainers.Count() == 0)
            {
                this.ViewData["Errors"] = GlobalConstants.NoTrainersErrorMessage;
            }

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChooseTrainer(UsernamesAndTrainerNameModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var currnetUser = await this.usersService.GetUserByUsernameAsync(this.User.Identity.Name);

            if (currnetUser.Weight == null || currnetUser.Height == null)
            {
                var modelForEditView = new ClientViewModel() { TrainerName = model.TrainerName };
                return this.View("EditWeightHeight", modelForEditView);
            }

            await this.usersService.SetTrainerAsync(model.TrainerName, this.User.Identity.Name);
            var trainer = await this.usersService.GetUsersTrainerAsync(this.User.Identity.Name);

            return this.View("MyTrainer", trainer);
        }

        public async Task<IActionResult> BecomeTrainer(string username)
        {
            var user = await this.usersService.GetUserByUsernameAsync(username);
            var futureTrainer = this.mapper.Map<ClientToTrainerBindingModel>(user);

            return this.View(futureTrainer);
        }

        [HttpPost]
        public async Task<IActionResult> BecomeTrainer(ClientToTrainerBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var result = await this.usersService.BecomeTrainerAsync(model, this.User.Identity.Name);

            if (!result)
            {
                return this.Redirect($"AreaClient/Client/BecomeTrainer?username={model.Username}");
            }

            await this.signInManager.SignOutAsync();
            return this.Redirect(GlobalConstants.Index);
        }

        public async Task<IActionResult> MyTrainer(string username)
        {
            var trainer = await this.usersService.GetUsersTrainerAsync(username);
            return this.View(trainer);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateWeightHeight(ClientViewModel model)
        {
            if (model.Weight <= 0 || model.Height <= 0)
            {
                this.ViewData["Errors"] = GlobalConstants.ErrorWeightHeightMessage;
                return this.View("EditWeightHeight", model);
            }

            await this.usersService.UpdateUserHeightAndWeightAsync(model, this.User.Identity.Name);
            await this.usersService.SetTrainerAsync(model.TrainerName, this.User.Identity.Name);

            var trainer = await this.usersService.GetUsersTrainerAsync(this.User.Identity.Name);
            return this.View("MyTrainer", trainer);
        }

        public async Task<IActionResult> LeaveTrainer(string trainerUsername)
        {
            await this.usersService.UnsetTrainerAsync(this.User.Identity.Name, trainerUsername);
            return this.Redirect(GlobalConstants.Index);
        }

        public async Task<IActionResult> MyFitnessPlan()
        {
            var fitnessPlan = await this.fitnessService.GetFitnessPlanByUsernameAsync(this.User.Identity.Name);
            return this.View(fitnessPlan);
        }
    }
}

Web/Olympia.Web/Areas/AreaShop/Controllers/ShopController.cs
namespace Olympia.Web.Areas.Shop.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Data.Models.ViewModels.Shop;
    using Olympia.Services.Contracts;

    using System.Linq;
    using System.Threading.Tasks;

    [Area(GlobalConstants.ShopArea)]
    [Authorize]
    public class ShopController : Controller
    {
        private readonly IShopService shopService;

        public ShopController(IShopService shopService)
        {
            this.shopService = shopService;
        }

        public async Task<IActionResult> ShopIndex()
        {
            var items = await this.shopService.GetAllItemsAsync();
            ShopViewModel shopViewModel = new ShopViewModel { Items = items };

            return this.View(shopViewModel);
        }

        public async Task<IActionResult> Items(string categoryName)
        {
            var items = await this.shopService.GetAllItemsByCategoryAsync(categoryName);

            foreach (var item in items)
            {
                item.Category = categoryName;
            }

            var shoppingCart = await this.shopService.GetShoppingCartByUserNameAsync(this.User.Identity.Name);
            var shopViewModel = new ShopViewModel() { Items = items, ShoppingCart = shoppingCart };

            return this.View("ItemsAll", shopViewModel);
        }

        public async Task<IActionResult> ItemDetails(int itemId, string category)
        {
            var item = await this.shopService.GetItemDtoByIdAsync(itemId);
            item.Category = category;

            return this.View(item);
        }

        public async Task<IActionResult> AddToCart(int itemId, string category)
        {
            var result = await
                this.shopService
                .AddItemToUserCartAsync(itemId, this.User.Identity.Name);

            if (!result)
            {
                this.ViewData["Errors"] = GlobalConstants.AlreadyAddedThisItem;
            }

            var cart = await this.shopService.GetShoppingCartByUserNameAsync(this.User.Identity.Name);
            var items = await this.shopService.GetAllItemsByCategoryAsync(category);

            ShopViewModel shopViewModel = new ShopViewModel
            {
                Items = items,
                ShoppingCart = cart
            };

            return this.View("ItemsAll", shopViewModel);
        }

        public async Task<IActionResult> ShoppingCart()
        {
            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);
            return this.View(cart);
        }

        public async Task<IActionResult> RemoveFromCart(int itemId)
        {
            await this.shopService.RemoveFromCartAsync(this.User.Identity.Name, itemId);
            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);

            return this.View("ShoppingCart", cart);
        }

        public async Task<IActionResult> IncreaseCount(int itemId)
        {
            await this.shopService.IncreaseTimesItemIsBoughtAsync(itemId);
            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);

            return this.View("ShoppingCart", cart);
        }

        public async Task<IActionResult> DecreaseCount(int itemId)
        {
            await this.shopService.DecreaseTimesItemIsBoughtAsync(itemId);
            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);

            return this.View("ShoppingCart", cart);
        }

        public async Task<IActionResult> FinishOrder()
        {
            var result = await this.shopService.FinishOrderAsync(this.User.Identity.Name);
            this.ViewData["Messages"] = GlobalConstants.SuccessfullOrderMessage;

            if (!result)
            {
                this.ViewData["Messages"] = GlobalConstants.NoItemsInCartMessage;
            }

            var cart = await this.shopService.GetShoppingCartDtoByUserNameAsync(this.User.Identity.Name);
            return this.View("ShoppingCart", cart);
        }

        public async Task<IActionResult> MyOrders()
        {
            var orders = await this.shopService.GetAllOrdersByUsernameAsync(this.User.Identity.Name);

            if (!orders.Any())
            {
                this.ViewData["Errors"] = GlobalConstants.NoOrdersMessage;
            }

            return this.View(orders);
        }

        public async Task<IActionResult> CompleteOrder(int orderId)
        {
            var result = await this.shopService.CompleteOrderAsync(orderId);

            if (!result)
            {
                this.ViewData["Errors"] = GlobalConstants.TooEarlyFinishOrderDate;
                var ordersToReturn = await this.shopService.GetAllOrdersByUsernameAsync(this.User.Identity.Name);

                return this.View("MyOrders", ordersToReturn);
            }

            var orders = await this.shopService.GetAllOrdersByUsernameAsync(this.User.Identity.Name);

            if (!orders.Any())
            {
                this.ViewData["Errors"] = GlobalConstants.NoOrdersMessage;
            }

            return this.View("MyOrders", orders);
        }
    }
}

Web/Olympia.Web/Controllers/AccountsController.cs
namespace Olympia.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using Olympia.Common;
    using Olympia.Data.Domain;
    using Olympia.Data.Models.BindingModels.Account;
    using Olympia.Data.Models.ViewModels.Home;
    using Olympia.Services.Contracts;

    using System.Threading.Tasks;

    public class AccountsController : Controller
    {
        private readonly SignInManager<OlympiaUser> signInManager;
        private readonly IAccountsServices accountsServices;
        private readonly IUsersService usersService;

        public AccountsController(
            SignInManager<OlympiaUser> signInManager,
            IAccountsServices accountsServices,
            IUsersService usersService)
        {
            this.signInManager = signInManager;
            this.accountsServices = accountsServices;
            this.usersService = usersService;
        }

        [AllowAnonymous]
        public IActionResult Register()
        {
            if (this.User.Identity.IsAuthenticated)
            {
                return this.Redirect(GlobalConstants.ErrorPage);
            }

            return this.View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(UserRegisterBingingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = await this.accountsServices.RegisterUserAsync(model);

            if (user == null)
            {
                this.ViewData["Errors"] = GlobalConstants.InvalidRegisterMessage;
                return this.View(model);
            }

            await this.signInManager.SignInAsync(user, isPersistent: true);
            return this.Redirect(GlobalConstants.Index);
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            if (this.User.Identity.IsAuthenticated)
            {
                return this.Redirect(GlobalConstants.ErrorPage);
            }

            return this.View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLoginBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = await this.accountsServices.LoginUserAsync(model);

            if (user == null)
            {
                this.ViewData["Errors"] = GlobalConstants.InvalidLoginMessage;
                return this.View();
            }

            return this.Redirect(GlobalConstants.Index);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await this.signInManager.SignOutAsync();
            return this.Redirect(GlobalConstants.Index);
        }
       
        [Authorize]
        public async Task<IActionResult> ProfileIndex()
        {
            var currentUser = await this.usersService.GetUserProfileModelAsync(this.User.Identity.Name);
            return this.View(currentUser);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> ProfileIndex(UserProfile model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.usersService.UpdateProfileAsync(model, this.User.Identity.Name);
            return this.Redirect(GlobalConstants.Index);
        }
    }
}

Web/Olympia.Web/Views/Shared/_AdministratorPartial.cshtml
<li class="nav-item">
    <a class="nav-link text-light"
       asp-area="AreaAdministration"
       asp-controller="Administration"
       asp-action="Index" title="Admin">Admin</a>
</li>
<li class="nav-item">
    <form class="form-inline"
          asp-area="Identity"
          asp-page="/Account/Logout">
        <button type="submit" class="nav-link btn btn-link text-light">Logout</button>
    </form>
</li>

Web/Olympia.Web/Views/Shared/_ClientPartial.cshtml
@if (this.context.Users.Include(x => x.Trainer).FirstOrDefault(x => x.UserName == this.User.Identity.Name).Trainer == null)
{
    <li class="nav-item active">
        <a class="nav-link text-light"
           asp-area="AreaClient"
           asp-controller="Client"
           asp-action="TrainersAll">Trainers</a>
    </li>
}
else
{
    <li class="nav-item active">
        <a class="nav-link text-light"
           asp-area="AreaClient"
           asp-controller="Client"
           asp-action="MyTrainer"
           asp-route-username="@this.User.Identity.Name">My Trainer</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link text-light"
           asp-area="AreaClient"
           asp-controller="Client"
           asp-action="MyFitnessPlan">My Fitness Plan</a>
    </li>
}
<li class="nav-item active">
    <a class="nav-link text-light"
       asp-controller="Accounts"
       asp-action="ProfileIndex">Profile</a>
</li>
<li class="nav-item active">
    <a class="nav-link text-light"
       asp-controller="Accounts"
       asp-action="Logout">Logout</a>
</li>

Web/Olympia.Web/Views/Shared/_CommonNavButtonsPartial.cshtml
@if (!this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{

    <li class="nav-item active">
        <a class="nav-link text-light"
           asp-area="AreaBlog"
           asp-controller="Blog"
           asp-action="ArticlesAll">Articles</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link text-light"
           asp-area="AreaShop"
           asp-controller="Shop"
           asp-action="MyOrders">My Orders</a>
    </li>
}


<li class="nav-item active">
    <a class="nav-link text-light"
       asp-area="AreaShop"
       asp-controller="Shop"
       asp-action="ShopIndex">Shop</a>
</li>

Web/Olympia.Web/Views/Shared/_GuestPartial.cshtml
<ul class="navbar-nav ml-auto">
    <li class="nav-item">
        <a class="nav-link text-light"
           asp-controller="Accounts"
           asp-action="Register">
            Register
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-light"
           asp-controller="Accounts"
           asp-action="Login">
            Login
        </a>
    </li>
</ul>

Web/Olympia.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Olympia</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-md navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Olympia</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_NavBarPartial" />

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="FAQ">FAQ</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Home" asp-action="Chat">Chat Room</a>
                            </li>
                        }
                        @if (this.User.IsInRole(GlobalConstants.ClientRoleName) &&
                             this.UserManager.Users
                                .FirstOrDefault(x => x.UserName == this.User.Identity.Name).Trainer == null &&
                             !this.User.IsInRole(GlobalConstants.TrainerRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light"
                                   asp-area="AreaClient"
                                   asp-controller="Client"
                                   asp-action="BecomeTrainer"
                                   asp-route-username="@this.User.Identity.Name">Become a trainer</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; @DateTime.Now.Year - Olympia.Web
        </div>
    </footer>

    <script src="jquery-3.4.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aspnet-signalr/1.1.4/signalr.js"></script>
    <script src="https://kit.fontawesome.com/ac2988e355.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/chat.js"></script>
    <script src="~/js/modals.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Olympia.Web/Views/Shared/_NavBarPartial.cshtml
@using Olympia.Common
@using Olympia.Data.Domain
@using Microsoft.AspNetCore.Identity
@inject SignInManager<OlympiaUser> SignInManager
@inject UserManager<OlympiaUser> UserManager

<div class="row">

    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="collapse navbar-collapse" id="navbarNav">
            @if (this.SignInManager.IsSignedIn(this.User))
            {
                <ul class="navbar-nav">
                    <partial name="_CommonNavButtonsPartial" />
                    @if (this.User.IsInRole(GlobalConstants.TrainerRoleName))
                    {
                        <partial name="_TrainerPartial" />
                    }
                    else if (this.User.IsInRole(GlobalConstants.ClientRoleName))
                    {
                        <partial name="_ClientPartial" />
                    }
                    else if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                    {
                        <partial name="_AdministratorPartial" />
                    }
                </ul>
            }
            else if (!this.User.Identity.IsAuthenticated)
            {
                <partial name="_GuestPartial" />
            }
        </div>
    </nav>
</div>

Web/Olympia.Web/Views/Shared/_TrainerPartial.cshtml
<li class="nav-item">
    <a class="nav-link text-light" 
       asp-area="AreaTrainer" 
       asp-controller="Trainer" 
       asp-action="ClientsAll">Clients</a>
</li>
<li class="nav-item active">
    <a class="nav-link text-light" 
       asp-area="AreaTrainer" 
       asp-controller="Trainer" 
       asp-action="MyArticles">My Articles</a>
</li>
<li class="nav-item active">
    <a class="nav-link text-light" 
       asp-controller="Accounts" 
       asp-action="ProfileIndex"> Profile</a>
</li>
<li class="nav-item">
    <form class="form-inline"
          asp-controller="Accounts"
          asp-action="Logout">
        <button type="submit" class="nav-link btn btn-link text-light">Logout</button>
    </form>
</li>